ok

diff --git a/Jenkinsfile.bak b/Jenkinsfile.bak
--- a/Jenkinsfile.bak
+++ b/Jenkinsfile.bak
@@ -1,7 +1,7 @@
 env.DOCKERHUB_USERNAME = 'ahsan0786'
   node("docker-test") {
     checkout scm
-    stage("Integration Test") {
+    stage("Testing imagenes") {
       try {
         sh " docker run --restart=always --name mysql -p 3307:3306 -v /home/ubuntu/docker/containers/mysql:/var/lib/mysql -e network_mode=proyecto -e MYSQL_ROOT_PASSWORD=Ausias123@@ -d ahsan0786/proyecto_mysql "
      sh "docker run --rm --name wordpress --link mysql:mysql -p 8080:80 -v /home/ubuntu/docker/containers/wordpress:/var/www/html -e network_mode=proyecto -e WORDPRESS_DB_HOST=mysql -e WORDPRESS_DB_USER=root -e WORDPRESS_DB_PASSWORD=Ausias123@@  -d ahsan0786/proyecto_wordpress"
@@ -14,7 +14,7 @@ env.DOCKERHUB_USERNAME = 'ahsan0786'
         sh "docker ps -aq | xargs docker rm || true"
       }
     }
-    stage("Publish") {
+    stage("Publicacion de imagenes") {
       withDockerRegistry([credentialsId: 'DockerHub']) {
 		sh "docker tag ahsan0786/proyecto_mysql ahsan0786/proyecto_mysql"
 		sh "docker tag ahsan0786/proyecto_wordpress ahsan0786/proyecto_wordpress"
@@ -27,7 +27,7 @@ env.DOCKERHUB_USERNAME = 'ahsan0786'
   node("docker-stage") {
     checkout scm
 
-    stage("Staging") {
+    stage("Testing contenedores") {
       try {
         sh " docker run --restart=always --name mysql -p 3307:3306 -v /home/ubuntu/docker/containers/mysql:/var/lib/mysql -e network_mode=proyecto -e MYSQL_ROOT_PASSWORD=Ausias123@@ -d ahsan0786/proyecto_mysql "
 	sh "docker run --rm --name wordpress --link mysql:mysql -p 8080:80 -v /home/ubuntu/docker/containers/wordpress:/var/www/html -e network_mode=proyecto -e WORDPRESS_DB_HOST=mysql -e WORDPRESS_DB_USER=root -e WORDPRESS_DB_PASSWORD=Ausias123@@  -d ahsan0786/proyecto_wordpress"
@@ -45,15 +45,15 @@ env.DOCKERHUB_USERNAME = 'ahsan0786'
   node("docker-prod") {
     stage("Production") {
       try {
-        // Create the service if it doesn't exist otherwisejust update the image
+        // comprueba si existe el servicio
         sh '''
          SERVICES=$(docker service ls --filter name=proyecto_mysql --quiet | wc -l)
 	 SERVICES1=$(docker service ls --filter name=proyecto_wordpress --quiet | wc -l)
           if [[ "$SERVICES" -eq 0 ]] && [[ "$SERVICES1" -eq 0 ]] ; then
 		docker network rm proyecto || true
 		docker network create --driver overlay --attachable proyecto
-		docker service create --replicas 1 --network proyecto --name proyecto_mysql -p 3306:3306 --mount type=bind,source=/home/ubuntu/docker/containers/mysql,destination=/var/lib/mysql --mount type=bind,source=/home/ubuntu/docker/containers/mysql-config/my.cnf,destination=/etc/mysql/my.cnf -e MYSQL_ROOT_PASSWORD=Ausias123@@ ahsan0786/proyecto_mysql
-		docker service create --replicas 3 --network proyecto --name proyecto_wordpress -p 80:80 --mount type=bind,source=/home/ubuntu/docker/containers/wordpress,destination=/var/www/html -e WORDPRESS_DB_HOST=proyecto_mysql -e WORDPRESS_DB_USER=root -e WORDPRESS_DB_PASSWORD=Ausias123@@ ahsan0786/proyecto_wordpress
+		docker service create --replicas 2 --network proyecto --name proyecto_mysql -p 3306:3306 --mount type=bind,source=/home/ubuntu/docker/containers/mysql,destination=/var/lib/mysql --mount type=bind,source=/home/ubuntu/docker/containers/mysql-config/my.cnf,destination=/etc/mysql/my.cnf -e MYSQL_ROOT_PASSWORD=Ausias123@@ ahsan0786/proyecto_mysql
+		docker service create --replicas 6 --network proyecto --name proyecto_wordpress -p 80:80 --mount type=bind,source=/home/ubuntu/docker/containers/wordpress,destination=/var/www/html -e WORDPRESS_DB_HOST=proyecto_mysql -e WORDPRESS_DB_USER=root -e WORDPRESS_DB_PASSWORD=Ausias123@@ ahsan0786/proyecto_wordpress
           else
 		docker service update --image ahsan0786/proyecto_mysql proyecto_mysql
 		docker service update --image ahsan0786/proyecto_wordpress proyecto_wordpress 
@@ -82,52 +82,20 @@ env.DOCKERHUB_USERNAME = 'ahsan0786'
       }catch(e) {
         sh "docker service update --rollback  proyecto_mysql"
 	sh "docker service update --rollback  proyecto_wordpress"
-        error "Service update failed in production"
+        error "Error en el nodo Prod"
       }
     }
   }
- 
-  node("docker-prod-slave") {
-    stage("Production") {
+  node("haproxy") {
+    stage("Loadb") {
       try {
-        // Create the service if it doesn't exist otherwise just update the image
-        sh '''
-          SERVICES=$(docker service ls --filter name=proyecto_mysql --quiet | wc -l)
-	  SERVICES1=$(docker service ls --filter name=proyecto_wordpress --quiet | wc -l)
-          if [[ "$SERVICES" -eq 0 ]] && [[ "$SERVICES1" -eq 0 ]] ; then
-		docker network rm proyecto || true
-		docker network create --driver overlay --attachable proyecto
-		docker service create --replicas 1 --network proyecto --name proyecto_mysql -p 3306:3306 --mount type=bind,source=/home/ubuntu/docker/containers/mysql,destination=/var/lib/mysql  --mount type=bind,source=/home/ubuntu/docker/containers/mysql-config/my2.cnf,destination=/etc/mysql/my.cnf -e MYSQL_ROOT_PASSWORD=Ausias123@@ ahsan0786/proyecto_mysql
-		docker service create --replicas 3 --network proyecto --name proyecto_wordpress -p 80:80 --mount type=bind,source=/home/ubuntu/docker/containers/wordpress,destination=/var/www/html -e WORDPRESS_DB_HOST=proyecto_mysql -e WORDPRESS_DB_USER=root -e WORDPRESS_DB_PASSWORD=Ausias123@@ ahsan0786/proyecto_wordpress
-          else
-		docker service update --image ahsan0786/proyecto_mysql proyecto_mysql
-            	docker service update --image ahsan0786/proyecto_wordpress proyecto_wordpress
-          fi
-          '''
-        // run some final tests in production
-        checkout scm
-        sh '''
-          sleep 60s 
-          for i in `seq 1 20`;
-          do
-		STATUS=$(docker service inspect --format '{{ .UpdateStatus.State }}' proyecto_mysql)
-		STATUS1=$(docker service inspect --format '{{ .UpdateStatus.State }}' proyecto_wordpress)
-            	if [[ "$STATUS" != "updating" ]] && [[ "$STATUS1" != "updating" ]]; then
-			docker run --restart=always --name mysql -p 3308:3306 -v /home/ubuntu/docker/containers/mysql:/var/lib/mysql -e network_mode=proyecto -e MYSQL_ROOT_PASSWORD=Ausias123@@ -d ahsan0786/proyecto_mysql
-			docker run --rm --name wordpress --link mysql:mysql -p 81:80 -v /home/ubuntu/docker/containers/wordpress:/var/www/html -e network_mode=proyecto -e WORDPRESS_DB_HOST=mysql -e WORDPRESS_DB_USER=root -e WORDPRESS_DB_PASSWORD=Ausias123@@  -d ahsan0786/proyecto_wordpress
-			docker stop mysql wordpress
-			docker rm mysql || true
-			docker rm mysql wordpress || true
-			break
-	        fi        
-            sleep 10s
-          done
-          
-        '''
+        // Levanta el container nginx
+	sh "docker stop nginx || true"
+	sh "docker rm nginx || true"
+	sh "docker run --name nginx -v /home/ubuntu/docker/containers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro -p 80:80 -d nginx nginx-debug -g 'daemon off;'"
+	checkout scm
       }catch(e) {
-        sh "docker service update --rollback  proyecto_mysql"
-	sh "docker service update --rollback  proyecto_wordpress"
-        error "Service update failed in production"
+        error "Error en el nodo LoadB"
       }
     }
   }
